Npm workspaces
eclipse/thingweb.node-wot pull request #483
Opened 2021-08-31 10:25 UTC by relu91

This PR refactor the current project structure using npm workspaces. As result of this refactoring `lerna` is no longer among our dev dependencies and everything has been ported to the new workspaces APIs. 

Open topics:
- Didn't test the publication procedure
- Didn't test CI (we'll see it after the creation of this PR)

Other points:
- After the refactoring npm added additional info to package.json of the bindings. I left that changes cause the were reasonable
- Opc-ua tests were not working, and I don't understand how the ever worked cause `url.origin` returns `'null'` with the current setup, and even testing online it returns the same ([see on runkit](https://runkit.com/embed/7grj9q5lpmxt)). I think the current code is more stable.

Closes #346

2021-08-31 13:08 UTC, danielpeintner commented
@relu91 I think the [issues](https://github.com/eclipse/thingweb.node-wot/pull/483/checks?check_run_id=3472929027) appear for nodejs version 10
see https://github.com/eclipse/thingweb.node-wot/blob/master/.github/workflows/ci.yaml#L13

Shall we remove `10.x` and add `16.x` ?

2021-08-31 13:31 UTC, danielpeintner commented
Note: I limited GitHub actions to LTS and current, see https://github.com/eclipse/thingweb.node-wot/commit/f398f79a3f567f2eebd7f260b25735a1cd896543

2021-08-31 13:42 UTC, egekorkan commented
Sadly not a super useful comment but when we were restructuring TD playground, we had considered both options. I don't exactly remember why but lerna was better _at the time_. There is this SO thread from 9 months ago: https://stackoverflow.com/questions/64909635/is-lerna-needed-anymore-with-npm-7-0-0s-workspaces

I have also read that lerna is having difficulties maintaining itself but was there a reason for the change?

2021-08-31 14:27 UTC, relu91 commented
> @relu91 I think the issues appear for nodejs version 10
see https://github.com/eclipse/thingweb.node-wot/blob/master/.github/workflows/ci.yaml#L13

It might be related but I am not sure is completely the problem. Before lunch I was digging into it, I've just finished a call and I'll try to understand what's going on. 

> Shall we remove 10.x and add 16.x ?

Looking around 10.x is considered outdated. I would completely ok to remove the support for it in 0.8.x. Is everybody ok with it? Should we open an issue and call for opinions? 

>Sadly not a super useful comment but when we were restructuring TD playground, we had considered both options. I don't exactly remember why but lerna was better at the time. There is this SO thread from 9 months ago: https://stackoverflow.com/questions/64909635/is-lerna-needed-anymore-with-npm-7-0-0s-workspaces
>
>I have also read that lerna is having difficulties maintaining itself but was there a reason for the change?

It seems that we read the same stackoverflow question and took different decisions. What I read there is that `lerna` is still useful but for complementary tooling and commands. Tools and commands that we don't use. In `node-wot` we mostly used `lerna` as a device for handling our monorepo. Consequently, I think moving to `workspaces` is the right choice here. A couple of thoughts:
- It is better supported (I don't think `npm` is going to die soon, plus is well founded)
- I like the symlink approach (also used by yarn) -> less disk space used
- just one `pakcage-lock.json` 
- It should be well integrated with the publishing workflow

What do you think?

2021-08-31 14:47 UTC, egekorkan commented
I see the advantages @relu91. We can just go ahead :)

2021-09-01 11:14 UTC, relu91 commented
Ok, I found out it's a well-known bug: https://github.com/npm/cli/issues/2632 . There's also a possible [workaround described](https://github.com/npm/cli/issues/2632#issuecomment-888960315), I am not a fan of it... but it is better than nothing 😄 .

2021-09-01 12:03 UTC, danielpeintner commented
@relu91 merging in master causes merge conflicts.. sorry for that

2021-09-01 12:22 UTC, relu91 commented
don't worry not a big deal 😄

2021-09-01 12:31 UTC, danielpeintner commented
Do you know why *no* GitHub jobs have been started?

Will do a local check also...

2021-09-01 12:34 UTC, relu91 commented
> Do you know why _no_ GitHub jobs have been started?
> 
> Will do a local check also...

It is probably because it was a merge commit... 🤔 but I checked on my fork. There was still a problem. Let's see if now it is solved

2021-09-01 13:08 UTC, relu91 commented
Just to keep you posted, one issue down. The current one is about typescript. It seems that in a clean repository it cannot find the types cause it actually builds the packages following the lexicographic order, not the dependency tree.

2021-09-01 15:24 UTC, relu91 commented
Ok, now it seems that the CI windows version does not like some native packages. I wasn't able to reproduce inside my machine yet. Let's see.

2021-09-02 10:31 UTC, danielpeintner commented on packages/binding-mbus/package.json
> +  "homepage": "https://github.com/thingweb/node-wot/tree/master/packages/binding-mbus#readme",
Link is broken,  should be
https://github.com/eclipse/thingweb.node-wot/tree/master/packages/binding-mbus#readme

2021-09-02 10:32 UTC, danielpeintner commented on packages/binding-modbus/package.json
> +  "homepage": "https://github.com/thingweb/node-wot/tree/master/packages/binding-modbus#readme",
Link broken also.. eclipse etc missing

2021-09-02 10:32 UTC, danielpeintner commented on packages/binding-netconf/package.json
> +  "homepage": "https://github.com/thingweb/node-wot/tree/master/packages/binding-netconf#readme",
Broken link

2021-09-02 10:35 UTC, danielpeintner commented on packages/binding-wotfirestore-browser-bundle/package.json
> +  },
Why does repository look different here, we seem to use something like this elsewhere

"repository": "https://github.com/eclipse/thingweb.node-wot/tree/master/packages/binding-wotfirestore",

2021-09-02 10:35 UTC, danielpeintner commented on packages/binding-wotfirestore-browser-bundle/package.json
> +  "keywords": []
Similar question, shouldn't it point to

https://github.com/eclipse/thingweb.node-wot/tree/master/packages/binding-wotfirestore

2021-09-02 10:36 UTC, danielpeintner commented on packages/binding-wotfirestore/package.json
> +  },
Similar comment, not pointing to package

2021-09-02 10:36 UTC, danielpeintner commented on packages/binding-wotfirestore/package.json
> +  "homepage": "https://github.com/hidetak/thingweb.node-wot#readme",
Similar comment, not pointing to package

2021-09-02 10:38 UTC, danielpeintner requested changes
See some broken links issues.
Also, I will run a local test and apart from that it looks good to me. thanks!

2021-09-02 12:00 UTC, danielpeintner commented
> I'll try to fix the m-bus issues before the end of next week. I'll let you know when I'm done with this and with #475

Thanks @LennyHEVS 
I created https://github.com/eclipse/thingweb.node-wot/issues/488 to keep track

2021-09-02 16:27 UTC, danielpeintner commented on packages/binding-mbus/package.json
> +    "url": "https://github.com/thingweb/node-wot/issues"
still wrong link

2021-09-02 16:27 UTC, danielpeintner commented on packages/binding-modbus/package.json
> +    "url": "https://github.com/thingweb/node-wot/issues"
link is wrong

2021-09-02 16:28 UTC, danielpeintner commented on packages/binding-netconf/package.json
> +    "url": "https://github.com/thingweb/node-wot/issues"
wrong also

2021-09-02 16:28 UTC, danielpeintner commented on packages/binding-opcua/package.json
> +    "url": "https://github.com/thingweb/node-wot/issues"
to be fixed

2021-09-03 12:36 UTC, relu91 commented
Another update, I tried to re-introduce mbus cause I think the real problem is the fact that the ci does not have the right window-build-tools installed. However, it seems that installing those tools on the ci is causing an infinite loop... I'll revert the commit and address @danielpeintner comments above.

2021-09-03 14:24 UTC, danielpeintner commented
I think we can go ahead merging this PR "as is" and solve mbus issues in a separate PR.
@relu91 if you agree please merge 👍

2021-09-03 14:56 UTC, merged