fix(binding-opcua): fix for #611
eclipse/thingweb.node-wot pull request #613
Opened 2021-11-08 17:07 UTC by lukesmolo

Fix for binding-opcua handling arrays (#611)

2021-11-08 17:44 UTC, relu91 approved these changes

2021-11-08 22:02 UTC, erossignon requested changes

2021-11-08 22:02 UTC, erossignon commented on packages/binding-opcua/src/opcua-client.ts
> +        const body = JSON.stringify(result, (k, v) => {
In fact, We should use const body = JSON.stringify(result.toJSON(), (k,v)=> ArrayBuffer.isView(v as ArrayLike<unknown>)? Array.from(v) : v);

2021-11-10 11:08 UTC, relu91 commented
Merging since @erossignon comment has been addressed.

2021-11-10 11:08 UTC, merged