chore(core): display info to better understand why schema validation …
eclipse/thingweb.node-wot pull request #665
Opened 2022-02-05 15:49 UTC by erossignon

this PR adds a tactical message to the console to help investigate why the AJV schema validation has failed.
Prior to this change, there was no way to detect why the system was throwing an exception. 

I am happy to replace this with a better mechanism, as console.log is not always welcome in production code. 
Please advice.

2022-02-05 15:54 UTC, relu91 requested changes
I think having this log message could help to understand what is going on. I would approve of this change. However, please follow the [logging guidelines](https://github.com/eclipse/thingweb.node-wot#logging) and don't forget to sign your commits 😃 . Thank you for your contribution!

2022-02-06 18:26 UTC, relu91 requested changes
From logging guidelines: 
> 2. Avoid to use info and log in packages other than the cli package.

I think the log messages you added should be logged under `console.debug` .

2022-02-07 10:10 UTC, relu91 approved these changes

2022-02-07 10:45 UTC, danielpeintner approved these changes

2022-02-07 10:45 UTC, merged