Fix browser example
eclipse/thingweb.node-wot pull request #686
Opened 2022-02-25 15:47 UTC by relu91

This PR introduces back the browser bundle among the supported packages. A couple of notes:
1. I discovered that `node-fetch` when used in browsers defaults to native `fetch` implementation this means the http client was sending `ReadableStreams` (instead of `Readable` from NodeJS) instance to the core. The core is expecting that every binding respect the contract of the `Content` interface which requires a NodeJS `Readable`. This PR changes `binding-http` to convert the stream before sending it the the `core`
2. `browserify` is using an old package for replacing nodejs `url` package. This creates issues when directly importing `url`. I discovered that using the global `URL` variable bypass `browserify` and it works well in browsers too. This PRs adds this workaround. Maybe #640 is another possible solution
3. I improved a little bit the example code and updated it
4. I fixed a bug when handling HTTP log polling requests from events. The servent was not handling head requests properly.

2022-02-25 17:08 UTC, relu91 commented on examples/browser/counter.js
> +            console.log("property: " + td.properties[property]);
Just noticed this left over, I'll update the pr after CI gives green light

2022-02-28 07:53 UTC, danielpeintner commented
Thanks @relu91 👍 

Note: No review, I still need to take a look. I just want to mention that there are 2 more "browser" examples we need to work on
* index
* smart-coffee-machine

We can tackle them in another PR. As you like @relu91?

2022-02-28 09:04 UTC, relu91 commented
Oh yeah, you're right I think we can do that in another PR!

2022-02-28 13:56 UTC, danielpeintner requested changes
I did run into some issues on my side
* a global `npm run build` does NOT create the dist folder for browser-bundle.
One needs to walk into packages\browser-bundle and call 
`npm run build` there to get `wot-bundle.min.js`
* When trying to run the counter.html I get several errors and the UI does not show
  - Uncaught TypeError: class heritage _$core_31.default is not an object or null
  - Uncaught ReferenceError: Wot is not defined

![grafik](https://user-images.githubusercontent.com/11281461/155995147-6c758982-ee43-45ec-a1f3-8645e5b58e52.png)

2022-02-28 16:21 UTC, relu91 commented
> a global npm run build does NOT create the dist folder for browser-bundle.
One needs to walk into packages\browser-bundle and call
npm run build there to get wot-bundle.min.js

Nice catch I didn't check for that sorry. Since the `browser-bundle` is not a TS project I've added the relevant commend in `build`.

> When trying to run the counter.html I get several errors and the UI does not show
Uncaught TypeError: class heritage _$core_31.default is not an object or null
Uncaught ReferenceError: Wot is not defined

It seems that is a `tinify` error... I temporally remove it but I think we should file an issue so that in the future we can understand what's going on.

2022-03-01 13:28 UTC, danielpeintner commented
> It seems that is a `tinify` error... I temporally remove it but I think we should file an issue so that in the future we can understand what's going on.

https://github.com/eclipse/thingweb.node-wot/issues/690 created

2022-03-01 13:29 UTC, danielpeintner approved these changes
Looks good!

Minor: do you want to remove the console.log ?

2022-03-02 18:03 UTC, merged