add code of conduct and security MD
eclipse/thingweb.node-wot pull request #691
Opened 2022-03-02 14:55 UTC by danielpeintner

fixes https://github.com/eclipse/thingweb.node-wot/issues/688

2022-03-02 14:56 UTC, danielpeintner commented
Note: I added the code of conduct "as is" from https://github.com/eclipse-ee4j/.github and simplified the security file a lot.

2022-03-02 18:06 UTC, relu91 requested changes
I agree with the changes but I've found a problem in the security document.

2022-03-02 18:06 UTC, relu91 commented on SECURITY.md
> +[Eclipse Security Policy](https://www.eclipse.org/security/policy.php).
I think this statement is not valid since we support only GitHub issues. Github issues are public which means that we can't limit the disclosure to just Eclipse Commiters.

2022-03-03 07:55 UTC, danielpeintner commented on SECURITY.md
> +[Eclipse Security Policy](https://www.eclipse.org/security/policy.php).
Good point!
I removed the disclosure limitation (since we act in public).

I wonder whether we need the whole section. Personally I don't think it hurts to list it again.
Opinions?

2022-03-04 09:42 UTC, relu91 approved these changes
I'm ok for keeping the section.

2022-03-04 14:46 UTC, merged