Support `uriVariables` at the root level
eclipse/thingweb.node-wot pull request #695
Opened 2022-03-11 11:16 UTC by relu91

2022-03-11 12:21 UTC, danielpeintner commented
Minor: coding style check fails

2022-03-14 09:46 UTC, danielpeintner requested changes
I wanted to update the counter example, see https://github.com/eclipse/thingweb.node-wot/commit/f68c03144d068333637063f460a006d1285c488e

I assume using global uriVariables should work but with this PR it does no longer work... can you check?

POST http://192.168.178.24:8080/counter/actions/increment?step=2 should increment by 2 .. but it does not.

2022-03-14 11:41 UTC, relu91 commented
> I assume using global uriVariables should work but with this PR it does no longer work... can you check?

I should update the counter example with your changes and understand why is not working anymore, right? Will do!

2022-03-14 12:04 UTC, danielpeintner commented
> I should update the counter example with your changes and understand why is not working anymore, right? Will do!

Yes, updating the counter with global uriVariables in this PR might be good 🙃

Somehow the variables are not passed along to the handler

2022-03-15 06:53 UTC, erossignon requested changes

2022-03-15 06:53 UTC, erossignon commented on packages/binding-coap/src/coap-server.ts
>      private isEmpty(obj: Record<string, unknown>) {
isEmpty doesn't depend on this and can be put outside the class as a simple function to avoid prototype pollution.

2022-03-15 06:53 UTC, erossignon commented on packages/binding-coap/src/coap-server.ts
> +    private parseUrlParameters(
can be static

2022-03-15 06:53 UTC, erossignon commented on packages/binding-http/src/http-server.ts
> +    private parseUrlParameters(
DRY: this is a duplication of coap-server#parseUrlParameter ?  may be a shared utility method is needed instead.

2022-03-15 06:53 UTC, erossignon commented on packages/binding-http/src/http-server.ts
> +    private parseUrlParameters(
DUplication of code

2022-03-17 09:04 UTC, danielpeintner approved these changes
LGTM now!
Thanks!

I will add the revised example with global uriVariables in another PR.

2022-03-17 09:04 UTC, merged