fix http client and server property "subscription"
eclipse/thingweb.node-wot pull request #922
Opened 2023-01-31 15:54 UTC by lifaon74

Hi, currently the `thing.observeProperty` was not working on the browser and server for the http binding.

- the HEAD header was not supported so I add it
- calling `.stop()` on the returned Subscription was not working. It came from the fact that the Client was not recycled and was generated each time by the Servient. => I'm not totally sure of this fix as it touches pretty abstract code.

Reviews are welcome

2023-02-01 08:55 UTC, relu91 commented
Hi! first of all, thank you really much for taking the time to give your contribution. Just some minor things before we can move on:
1. Since this is an eclipse project new contributors have to sign the Eclipse Contributor Agreement ( see [how to contribute](https://github.com/eclipse/thingweb.node-wot/blob/master/CONTRIBUTING.md#legal-requirements) and let us know if there are any problems). 
2. Even after your last commit there are still some linting errors, can you fix them too? 

Regarding the first issue, I think the changes look good but I would need some time to verify the second point.

2023-02-01 09:29 UTC, lifaon74 commented
Done.

2023-02-01 10:44 UTC, danielpeintner reviewed
Looking at the code I do not see any obvious issue. 👍 
However I would like to wait for @relu91 to take a closer look.

Two questions:
* You mentioned the issue was in browser only but do you think a test could be created in [binding-http](https://github.com/eclipse/thingweb.node-wot/tree/master/packages/binding-http/test) that fails before this change?
* Is the change for `package-lock.json` actually needed. I do not really understand why it is there. I think there is no need.

Thanks!

2023-02-01 11:43 UTC, lifaon74 commented
1) before my change, the `thing.observeProperty` was returning a promise which never resolved. Indeed, the on the LongPollingSubscription the 'resolve' was only called when the 'HEAD' request success (which never appends).
Moreover, the calling `stop` on the returned Subscription was not working neither, because a new HttpClient was created each time. Thus, no "internal" Subscriptions were existing, and the cancel was never done.

2) Probably not. However, I suggest you to add a `.nvmrc` file with a specific version of node (ex: `v16`), this way, running `nvm use` followed by `npm i` for new incomers will generate the same package-lock instead of an updated one. As, I was not aware of which node version to use for the project, I used `16.19.0` LTS

2023-02-02 08:47 UTC, danielpeintner commented
> 2\. Probably not. However, I suggest you to add a `.nvmrc` file with a specific version of node (ex: `v16`), this way, running `nvm use` followed by `npm i` for new incomers will generate the same package-lock instead of an updated one. As, I was not aware of which node version to use for the project, I used `16.19.0` LTS

I see your points. Anyhow, we state in our [README](https://github.com/eclipse/thingweb.node-wot#as-a-standalone-application) that people should call `npm ci` (instead of `npm i`)

Note: I believe even with a version set in `.nvmrc` you may end up creating slight changes in `package-lock.json` since packages might have been updated etc.

Can you please remove the changes in `package-lock.json`. Thanks!

2023-02-04 17:51 UTC, lifaon74 commented
Updated

2023-02-09 15:56 UTC, relu91 requested changes
First of all, thank you for reporting and providing a solution for the issue. However, your solution for point number 2, has the side effect of caching clients for every operation. We lately discussed it in https://github.com/eclipse/thingweb.node-wot/issues/904 and we decided that is something that the binding level should decide. 

Even though the current core-protocol interface is far to be perfect a more conservative approach to solve the issue is to store the client in `InternalSubscription` class inside `ConsumedThing`. May I ask you to propose such a change?

2023-02-10 16:20 UTC, lifaon74 commented
Hi, sadly I'm not confident enough to make such an update. The code is pretty opaque to me, and probably result of design choices that I'm not aware.

2023-02-10 21:26 UTC, relu91 commented
hey! no problem at all. We'll update the PR accordingly and merge it asap. thank u again.

2023-02-16 16:45 UTC, relu91 commented
Did a quick fix, @lifaon74 can you test it?

2023-02-17 08:10 UTC, relu91 approved these changes

2023-02-20 10:06 UTC, danielpeintner commented
It looks good to me. I hope @lifaon74 can provide feedback whether it solves the issues he encountered.

2023-02-20 10:06 UTC, danielpeintner approved these changes

2023-02-27 09:18 UTC, merged