Pull Request for asset-interface-description.ts file
eclipse/thingweb.node-wot pull request #927
Opened 2023-02-13 15:56 UTC by Kaz040

Hello, to start with, I am completely  new to JS and TS and this is my first time make a PR.  

When I was trying to test Modubs implementation of AID in node-wot, I bumped into a bug, the AID <-> TD code did not consider **qualifier** of each datapoints in AID. we actually include the valueType there which corresponds to the TD dataschema **type**.

So, I added a little line of codes in asset-interface-description.ts file to include the datatype modelled in AID for TD properties.  i did for only properties because the final for how to model the data type has not been made but it is important for modbus testing due to its payload type(octet-stream). 

Thank you and Regards.

2023-02-14 09:28 UTC, danielpeintner commented
Hi @Kaz040. Thanks for your contribution 👍.

Some points.
* You need to sign Eclipse ECA as described in [CONTRIBUTING.md](https://github.com/eclipse/thingweb.node-wot/blob/master/CONTRIBUTING.md) before we can merge/accept any PR.
* Can you provide a test-case in [AssetInterfaceDescriptionTest.ts](https://github.com/eclipse/thingweb.node-wot/blob/master/packages/td-tools/test/AssetInterfaceDescriptionTest.ts) so that we can better understand what currently does not work as expected. Thanks!

2023-02-22 08:43 UTC, danielpeintner requested changes
I think we are getting close 👍.

Unfortunately, the Eclipse ECA check still fails... maybe because of the commit history. *All* commits need to be done with the email address registered at Eclipse. If you are failing to resolve, a complete *new* PR with the right commit history might be another solution.

BTW, I added 2 more minor comments.

2023-02-22 08:43 UTC, danielpeintner commented on packages/td-tools/test/AssetInterfaceDescriptionTest.ts
> +        // just inserter by Kaz
I guess a description what it checks is better than a name...

2023-02-22 08:43 UTC, danielpeintner commented on packages/td-tools/src/util/asset-interface-description.ts
> +                logInfo("vProperty" + key + " = " + value);
I believe this change is unintended

2023-02-22 08:49 UTC, danielpeintner commented on packages/td-tools/src/util/asset-interface-description.ts
> +                    if (vi.interaction.constraints instanceof Array && vi.interaction.constraints) {
I believe the order of the checks should change, first null/undefined check and then whether it is array.

2023-02-22 09:19 UTC, Kaz040 commented
Hello Daniel.

Thank you for your input and comments. I will make necessary adjustments and get back.

2023-02-22 10:20 UTC, closed without merging

2023-02-22 13:38 UTC, danielpeintner commented
Note: replaced by https://github.com/eclipse/thingweb.node-wot/pull/929