Explain usage of online Things
eclipse/thingweb.node-wot pull request #967
Opened 2023-04-28 16:44 UTC by egekorkan

fixes #956

2023-05-02 11:53 UTC, danielpeintner commented on README.md
> +-   [Eclipse Thingweb node-wot](#eclipse-thingweb-node-wot)
I don't think this additional nesting is necessary.

2023-05-02 11:53 UTC, danielpeintner commented on README.md
> +    -   [Table of Contents](#table-of-contents)
I don't think we need TOC in TOC...

2023-05-02 11:54 UTC, danielpeintner commented on README.md
> +        -   [Regenerating package-lock.json](#regenerating-package-lockjson)
I would not add internals link either..

2023-05-02 11:55 UTC, danielpeintner requested changes
I think the *actual* change "Online Things" is fine.
What I would mostly roll-back are the changes to the TOC

2023-05-02 21:36 UTC, egekorkan commented
I have fixed the issue. It seems that my vs code auto generates ToC at each save...

2023-05-03 05:54 UTC, danielpeintner approved these changes

2023-05-03 11:51 UTC, relu91 approved these changes

2023-05-03 11:51 UTC, merged