fix: report SVG values without quotes
eclipse/thingweb.node-wot pull request #981
Opened 2023-05-08 13:29 UTC by danielpeintner

fixes https://github.com/eclipse/thingweb.node-wot/issues/965

2023-05-08 13:32 UTC, danielpeintner commented
Note: I think it is a very hack fix and I am not sure what we can/should to else.

`Buffer.from("XXX");`

returns a buffer of the `XXX` string around with quotes.

2023-05-09 06:44 UTC, danielpeintner commented on packages/core/src/codecs/text-codec.ts
> +            if (this.subMediaType === "image/svg+xml" && typeof value === "string") {
Question: Maybe we can add an option in the TextCodec constructor whether wrapping is needed or not. That makes it more generic. What do you think?

2023-05-10 07:05 UTC, danielpeintner commented on packages/core/src/codecs/text-codec.ts
> +            if (this.subMediaType === "image/svg+xml" && typeof value === "string") {
Created `bufferDirectWrite` options since it is needed for HTML, SVG etc as well..

2023-05-10 10:18 UTC, relu91 requested changes
Checked https://datatracker.ietf.org/doc/html/rfc822#appendix-A and it seems that also text/plain does not require quotes around the body, so I think we can get rid of the boolean modifier and always return the unquoted value. 

Also as a solution to the issue, instead of checking if the value in input is a string and doing Buffer manipulation, why don't we do the following:
```ts
        let body = "";
        if (value !== undefined && typeof(value) === 'string') {
            body = value
        } else {
            body = JSON.stringify(value)
        }
```

2023-05-11 06:45 UTC, danielpeintner commented
@relu91 I integrated you proposed changes. Please have a look.

2023-05-11 13:54 UTC, relu91 approved these changes
LGTM

2023-05-11 13:54 UTC, merged